site_name: Документация Reticulum

# Ссылка на репозиторий (добавляет иконку в шапку)
repo_url: https://github.com/kirillz/reticulum-docs
repo_name: kirillz/reticulum-docs

theme:
  name: material
  language: ru
  include_homepage_in_sidebar: false
  font:
    code: Roboto Mono
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Автоматически как в Системе
    # Светлая тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Переключить на темную тему
    # Темная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Переключить на светлую тему
  icon:
    logo: material/book-open-page-variant


# Структура меню
nav:
  - Главная: index.md
  - RNS:
      - Основы: rns/index.md
      - Словарь терминов: rns/glossary.md
      - Утилиты:
          - Обзор: rns/tools/index.md
          - rnsd (Демон): rns/tools/rnsd.md
          - rnstatus (Статус): rns/tools/rnstatus.md
          - rnid (Идентификаторы): rns/tools/rnid.md
          - rnpath (Маршруты): rns/tools/rnpath.md
          - rnprobe (Диагностика): rns/tools/rnprobe.md
          - rncp (Копирование файлов): rns/tools/rncp.md
          - rnx (Удаленное выполнение): rns/tools/rnx.md
          - rnsh (Оболочка): rns/tools/rnsh.md
          - rnodeconf (RNode): rns/tools/rnodeconf.md
      - Обнаружение: rns/discovery.md
      - Управление: rns/management.md
      - Конфигурирование: rns/improving.md
      - Оборудование: rns/hardware.md
      - Blackhole: rns/blackhole.md
  - LXMF:
      - Основы: lxmf/index.md
      - Утилиты:
          - Обзор: lxmf/tools/index.md
          - lxmd (Узел распространения): lxmf/tools/lxmd.md
  - Nomad Network: nomadnet/index.md

plugins:
  - search          # Обязательно возвращаем поиск при использовании своих плагинов
  - git-revision-date-localized:
      enable_creation_date: false
      type: datetime
  - glightbox:
      background: light
      shadow: true
      effect: zoom
# Кастомные стили
extra_css:
  - css/custom.css

# Настройки Markdown
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - attr_list       # Нужно для иконок и кнопок
  - md_in_html      # Нужно для карточек (div)
  - pymdownx.emoji: # Нужно для смайликов-иконок :material-...:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg # Убираем надпись "Made with Material for MkDocs"

extra:
  generator: false
